version: "3"

services:
  db:
    container_name: couser_java_spring_boot
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'store'
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
