INSERT INTO UNIDAD_MEDIDA (DESCRIPCION) VALUES ('GRAMOS'),('KILOGRAMOS'),('LITROS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('TEXTILES'), ('LICORES'), ('ELECTRODOMESTICOS')


INSERT INTO USER (nickname, password, nombre) VALUES('admin','$2a$10$t/PdA/3Si76ocOFCdDSZj.qDw0u063lsrNv./fw4E2O9JYS5I1EAu','test')

